branches:
  only:
    - master

language: android

sudo: false

cache: false

env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=default/armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=8 # 2 is default - and currently not enough for Travis-CI

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - android-22
    - sys-img-armeabi-v7a-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb logcat -v time > logcat.txt &

script:
  - ./gradlew build testDebug connectedCheck --continue --info

after_script:
  - travis_fold:start:logcat
  - cat logcat.txt
  - travis_fold:end:logcat

after_success:
  - ./gradlew createDebugCoverageReport