branches:
  only:
    - master

language: java
sudo: false

jdk:
  - oraclejdk8

script:
  - ./gradlew spork:check spork-mockito:check --continue --info

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

after_success:
- echo success