branches:
  only:
    - master
    - 2.0.0

language: java
sudo: false

jdk:
  - oraclejdk8
 
script:
  - ./gradlew check --continue --info

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

after_success:
- ./gradlew jacocoTestReport coveralls