language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - build-tools-25.0.2
    - android-25
jdk: oraclejdk8
script: ./gradlew check