# General configuration

language: android
sudo: false

# Development dependencies

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - build-tools-25.0.2
    - android-25

# Tasks

script: ./gradlew check

# Caching

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
