# General configuration

language: android
sudo: false

# Development dependencies

jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # override 2 minute default
    - QEMU_AUDIO_DRV=none # disable emulator audio to avoid warning
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle" # change location for Gradle Wrapper and cache
    - ANDROID_HOME=/usr/local/android-sdk-24.0.2 # depends on the cookbooks version used in the VM
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

android:
  components:
    - tools # Update preinstalled tools from revision 24.0.2 to 24.4.1
    - build-tools-25.0.3
    - platform-tools
    - tools # Update tools from revision 24.4.1 to 25.2.5

install:
  - sdkmanager --list || true
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "system-images;android-21;default;armeabi-v7a"
  - echo yes | sdkmanager "platforms;android-25"
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

# Pipeline

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a --skin 480x800
  - emulator -avd test -no-skin -no-audio -no-window -gpu off &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew check connectedCheck

# Caching

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache